language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix

before_script:
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' > $(php --ini|grep -m 1 "ini files in:"|cut -d ":" -f 2)/sendmail.ini
  - composer selfupdate
  - composer install

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

notifications:
  email: false
