language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer selfupdate
  - composer install
  - sudo apt-get update
  - sudo apt-get install mailutils

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
